require('core.plugconfig.theme')
require('core.plugconfig.lualine')
require('core.plugconfig.nvim-tree')
require('core.plugconfig.treesitter')
require('core.plugconfig.telescope')
require('core.plugconfig.lsp_config')
require('core.plugconfig.completion')
require('core.plugconfig.gitsigns')
require('core.plugconfig.bufferline')
require('core.plugconfig.autotag')
require('core.plugconfig.emmet')
require('core.plugconfig.vimwiki')
-- require('core.plugconfig.gdscript')
